#! /usr/bin/env python
# encoding: utf-8

# Test with the kodo-c static library
bld.program(
    features='cxx test',
    source=['kodoc_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
    target='../kodoc_static_tests',
    use=['kodoc_static', 'gtest'])
